<?php
// initializes or resumes a session, allowing you to store and retrieve session data.
session_start();
// turns on output buffering, which captures output generated by PHP scripts.
ob_start();
?>

<div class="container mt-5">
    <div class="text-center">
        <h1 class="display-6">Destinasi Pariwisata Banyuwangi</h1>
    </div>
</div>

<div class="row container mt-5 dataPariwisataBanyuwangi"></div>

<script>
    //  fetches data from a backend endpoint asynchronously using AJAX, 
    // dynamically generates HTML content based on the fetched data, 
    // and updates a specific element on the webpage with the generated content.
    $(document).ready(function() {
        $.ajax({
            type: "GET",
            url: "/jwd/backend/wisata.php",
            success: function(response) {
                const data = response
                let html = ''
                if (data.length > 0) {
                    data.forEach(pariwisata => {
                        html += `
            <div class="col-md-4 d-flex align-items-stretch">
              <div class="card flex-grow-1 m-2" style="width: 18rem;">
                <img src="/jwd/backend/assets/img/${pariwisata?.img}" class="card-img-top" alt="${pariwisata?.nama}" />
                <div class="card-body">
                  <h5 class="card-title">${pariwisata?.nama}</h5>
                  <a href="/jwd/page/customer/form.php" class="btn btn-success">Pesan Sekarang</a>
                  <a href="${pariwisata?.link}" target="_blank" class="btn btn-primary">Lihat Detail</a>
                </div>
              </div>
            </div>
            `;
                    });
                } else {
                    html = '<h1 class="text-center">Data Kosong</h1>'
                }
                $('.dataPariwisataBanyuwangi').html(html)
            }
        });
    });
</script>

<style>
    /* provided creates a hover effect for elements with the class .card,
    causing them to increase in size by 5% with a smooth transition animation over a duration of 0.5 
    seconds when hovered over by the user. */
    .card:hover {
        transform: scale(1.05);
        transition: transform 0.5s;
    }
</style>

<!-- This PHP code retrieves the buffered content using the `ob_get_clean()` function, which captures the output buffer content and then clears it. 
The retrieved content is stored in the `$content` variable. 
Subsequently, it includes the `index.php` file located in the `page/components` directory using the `require` statement. 
This file is likely responsible for rendering the HTML structure and incorporating the retrieved content within it, facilitating dynamic content rendering on the webpage. 
Overall, this script completes the rendering process by integrating the dynamic content with the HTML structure defined in the `index.php` component file. -->
<?php
$content = ob_get_clean();
require './page/components/index.php';
?>