<?php
// initializes or resumes a session, allowing you to store and retrieve session data.
session_start();
// turns on output buffering, which captures output generated by PHP scripts.
ob_start();
?>

<div class="container mt-5">
    <div class="text-center">
        <h1 class="display-6">Daftar Kamar Hotel</h1>
    </div>
</div>

<div class="row mt-5 mx-5 dataPariwisataBanyuwangi"></div>

<div class="modal modalDetail" tabindex="-1" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<script>
    let allData = []
    //  fetches data from a backend endpoint asynchronously using AJAX, 
    // dynamically generates HTML content based on the fetched data, 
    // and updates a specific element on the webpage with the generated content.
    $(document).ready(function() {
        $.ajax({
            type: "GET",
            url: "/backend/kamar.php",
            success: function(response) {
                allData = response
                let html = ''
                if (allData.length > 0) {
                    allData.forEach(pariwisata => {
                        html += `
            <div class="col-md-4 d-flex align-items-stretch">
              <div class="card flex-grow-1 m-2">
                <img src="/backend/assets/img/${pariwisata?.img}" class="card-img-top" alt="${pariwisata?.nama}" />
                <div class="card-body">
                  <h5 class="card-title">${pariwisata?.nama}</h5>
                  <p class="card-text">${currencyRupiah(pariwisata?.harga)}</p>
                  <a href="/page/customer/form.php" class="btn btn-success">Pesan Sekarang</a>
                  <a onclick="openDetail(${pariwisata.id})" class="btn btn-primary">Lihat Detail</a>
                </div>
              </div>
            </div>
            `;
                    });
                } else {
                    html = '<h1 class="text-center">Data Kosong</h1>'
                }
                $('.dataPariwisataBanyuwangi').html(html)
            }
        });
    });

    // This code defines a
    // function named `openDetail` in JavaScript, which takes a parameter `data`.It searches
    // for an object within the `allData`
    // array whose `id`
    // matches the provided `data`, utilizing the `findIndex`
    // method.If a matching object is found, it logs the corresponding object to the console and populates a modal with details extracted from the found object, such as its `nama`(name) and a YouTube video embedded within an iframe sourced from the object 's `link` property. Finally, it displays the modal to the user using Bootstrap modal functionality.
    const openDetail = (data) => {
        const idx = allData.findIndex(x => x.id == data)
        console.log(allData[idx])
        $('.modalDetail .modal-title').text(allData[idx].nama)
        $('.modalDetail .modal-body').html(`
        <iframe width="100%" height="100%" src="${allData[idx]?.link}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
        `)
        $('.modalDetail').modal('show')
    }
</script>

<style>
    /* provided creates a hover effect for elements with the class .card,
    causing them to increase in size by 5% with a smooth transition animation over a duration of 0.5 
    seconds when hovered over by the user. */
    .card:hover {
        transform: scale(1.05);
        transition: transform 0.5s;
    }

    .card-img-top {
        height: 200px;
        object-fit: cover;
    }

    .modal-body {
        height: 500px;
    }

    /* change media query card for desktop */
    @media (min-width: 768px) {
        .card {
            width: 500px;
        }

        .card-img-top {
            height: 300px;
        }
    }
</style>

<!-- This PHP code retrieves the buffered content using the `ob_get_clean()` function, which captures the output buffer content and then clears it. 
The retrieved content is stored in the `$content` variable. 
Subsequently, it includes the `index.php` file located in the `page/components` directory using the `require` statement. 
This file is likely responsible for rendering the HTML structure and incorporating the retrieved content within it, facilitating dynamic content rendering on the webpage. 
Overall, this script completes the rendering process by integrating the dynamic content with the HTML structure defined in the `index.php` component file. -->
<?php
$content = ob_get_clean();
require './page/components/index.php';
?>