<?php
// initializes or resumes a session, allowing you to store and retrieve session data.
session_start();
// turns on output buffering, which captures output generated by PHP scripts.
ob_start();
?>

<div class="container mt-5">
    <div class="text-center">
        <h1 class="display-6">Destinasi Pariwisata Banyuwangi</h1>
    </div>
</div>

<div class="row my-5">
    <div class="col-md-8 col-xs-12">
        <div class="row mt-5 mx-5 dataPariwisataBanyuwangi"></div>
    </div>
    <div id="iframeContainer" class="col-md-4 mt-5 col-xs-12">
        <iframe width="80%" height="25%" src="https://www.youtube.com/embed/h4jSA8i9UUA?si=8J6ZOsn0cGh7q5LE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
        <iframe width="80%" height="25%" src="https://www.youtube.com/embed/xuhLZcnHN1E?si=-CLINNwMnkdifqIE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>
</div>

</div>

<script>
    //  fetches data from a backend endpoint asynchronously using AJAX, 
    // dynamically generates HTML content based on the fetched data, 
    // and updates a specific element on the webpage with the generated content.
    $(document).ready(function() {
        $.ajax({
            type: "GET",
            url: "/jwd/backend/wisata.php",
            success: function(response) {
                const data = response
                let html = ''
                if (data.length > 0) {
                    data.forEach(pariwisata => {
                        html += `
            <div class="col-md-4 d-flex align-items-stretch">
              <div class="card flex-grow-1 m-2">
                <img src="/jwd/backend/assets/img/${pariwisata?.img}" class="card-img-top" alt="${pariwisata?.nama}" />
                <div class="card-body">
                  <h5 class="card-title">${pariwisata?.nama}</h5>
                  <a href="/jwd/page/customer/form.php" class="btn btn-success">Pesan Sekarang</a>
                  <a href="${pariwisata?.link}" target="_blank" class="btn btn-primary">Lihat Detail</a>
                </div>
              </div>
            </div>
            `;
                    });
                } else {
                    html = '<h1 class="text-center">Data Kosong</h1>'
                }
                $('.dataPariwisataBanyuwangi').html(html)
            }
        });
    });

    // Function to check if the device is a phone
    function isPhone() {
        return window.matchMedia("(max-width: 575.98px)").matches;
    }

    // Function to add the class d-flex justify-content-center if it's a phone
    function addFlexCenterClass() {
        var iframeContainer = document.getElementById('iframeContainer');
        if (isPhone()) {
            iframeContainer.classList.add('d-flex', 'justify-content-center');
        }
    }

    // Call the function when the page loads
    window.onload = function() {
        addFlexCenterClass();
    };
</script>

<style>
    /* provided creates a hover effect for elements with the class .card,
    causing them to increase in size by 5% with a smooth transition animation over a duration of 0.5 
    seconds when hovered over by the user. */
    .card:hover {
        transform: scale(1.05);
        transition: transform 0.5s;
    }

    /* change media query card for desktop */
    @media (min-width: 768px) {
        .card {
            width: 500px;
        }
    }
</style>

<!-- This PHP code retrieves the buffered content using the `ob_get_clean()` function, which captures the output buffer content and then clears it. 
The retrieved content is stored in the `$content` variable. 
Subsequently, it includes the `index.php` file located in the `page/components` directory using the `require` statement. 
This file is likely responsible for rendering the HTML structure and incorporating the retrieved content within it, facilitating dynamic content rendering on the webpage. 
Overall, this script completes the rendering process by integrating the dynamic content with the HTML structure defined in the `index.php` component file. -->
<?php
$content = ob_get_clean();
require './page/components/index.php';
?>